apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-hello-app-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/kuuhaku86/go-hello-app
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/kuuhaku86/gitops-infra-cluster
    targetRevision: main
    path: apps/overlays/prod
  destination:
    name: prod
    namespace: go-hello-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
