apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-hello-app-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/kuuhaku86/go-hello-app
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/kuuhaku86/gitops-infra-cluster
    targetRevision: main
    path: apps/overlays/staging
  destination:
    server: https://172.19.0.7:6443
    namespace: go-hello-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
