apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-hello-app-staging
nameSuffix: -staging
resources:
  - namespace.yaml
  - ../../base
images:
  - name: ghcr.io/kuuhaku86/go-hello-app
    newTag: latest
patches:
  - path: patches.yaml
